image: tiangolo/docker-with-compose:latest

stages:
  - build-docs
  - build-docker
  - deploy

build:site:
  stage: build-docs
  image:
    name: squidfunk/mkdocs-material
    entrypoint: [""]
  artifacts:
    paths:
      - site
  script:
    - mkdocs build

build:docker:
  stage: build-docker
  dependencies:
    - build:site
  script:
    - docker-compose build

deploy:docker:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up -d
