site_name: FatalDream Docs
plugins:
    - search
    - minify:
          minify_html: true
          minify_js: true
          htmlmin_opts:
              remove_comments: true
    - git-revision-date-localized:
          #   enabled: !ENV [CI, false]
          enable_creation_date: true
          type: date
    - git-committers:
          #   enabled: !ENV [CI, false]
          repository: FatalDream/docs
          branch: main

theme:
    name: material
    logo: assets/logo.svg
    favicon: assets/logo.png
    palette:
        - scheme: slate
          primary: black
          accent: pink
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
        - scheme: default
          primary: black
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.tracking
        - navigation.tabs
        - navigation.top
        - navigation.sections
        - navigation.indexes
        - toc.follow
        - content.action.edit
        - content.action.view
    icon:
        repo: fontawesome/brands/github
        edit: material/pencil
        view: material/eye

markdown_extensions:
    - toc:
          permalink: ⚓︎
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list

extra_css:
    - stylesheets/extra.css

repo_url: https://github.com/FatalDream/docs
repo_name: FatalDream/docs
edit_uri: edit/main/docs
nav:
    - Welcome: "index.md"
    - SecondCraft:
          - SecondCraft/getting-started.md
          - Alternative Installation: SecondCraft/alternative-install.md
          - SecondCraft/server-ip.md
          - SecondCraft/dynmap.md
          - SecondCraft/fuel-efficency.md
          - Voice Chat and Radios: SecondCraft/vc-radios.md
          - Fuel Pumps: SecondCraft/fuelpumps.md
          - Mine Location: SecondCraft/minelocation.md
          - Donate: SecondCraft/donate.md
