site_name: FatalDream Docs
plugins:
    - search
    - minify:
          minify_html: true
          minify_js: true
          htmlmin_opts:
              remove_comments: true
theme:
    name: material
    logo: assets/logo.svg
    palette:
        - scheme: slate
          primary: black
          accent: pink
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
        - scheme: default
          primary: black
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.top

markdown_extensions:
    - toc:
          permalink: ⚓︎
    - admonition
    - pymdownx.details
    - pymdownx.superfences

extra_css:
    - stylesheets/extra.css
